global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: reddit-mcp
    metrics_path: /metrics
    static_configs:
      - targets: ["app:8000"]

  # Example exporters can be added here as needed

